name: Build Release APK Files
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - uses: actions/checkout@v3

      # Setup Java for Flutter
      - uses: actions/setup-java@v3
        with:
          java-version: "17.x"
          distribution: "temurin"
          cache: gradle

      # Install Flutter command
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release

      # Add APk to assets
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN_SECRET }}
